-- 创建反馈表
CREATE TABLE IF NOT EXISTS feedbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  feedback_type VARCHAR(50) NOT NULL, -- bug_report, new_game, new_tool, suggestion
  content TEXT NOT NULL,
  images TEXT[] DEFAULT '{}', -- 图片URL数组
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_feedbacks_user_id ON feedbacks(user_id);
CREATE INDEX IF NOT EXISTS idx_feedbacks_type ON feedbacks(feedback_type);
CREATE INDEX IF NOT EXISTS idx_feedbacks_created_at ON feedbacks(created_at DESC);

-- 启用行级安全
ALTER TABLE feedbacks ENABLE ROW LEVEL SECURITY;

-- 策略：用户可以查看和创建自己的反馈
CREATE POLICY "Users can view own feedbacks" ON feedbacks
  FOR SELECT USING (auth.uid()::text = user_id::text);

CREATE POLICY "Users can create own feedbacks" ON feedbacks
  FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

-- 策略：管理员可以查看所有反馈（需要有管理员角色）
CREATE POLICY "Admins can view all feedbacks" ON feedbacks
  FOR SELECT USING (auth.uid() IN (SELECT id FROM users WHERE role = 'admin'));
