-- 创建桌游规则表（支持多格式：Markdown / 图片）
CREATE TABLE IF NOT EXISTS game_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT NOT NULL REFERENCES board_games(id) ON DELETE CASCADE,
  title VARCHAR(128) NOT NULL,
  rule_type VARCHAR(16) NOT NULL DEFAULT 'markdown', -- 'markdown' | 'images'
  content TEXT,                                      -- Markdown 内容（仅 rule_type=markdown）
  image_urls JSONB DEFAULT '[]',                     -- 图片 URL 数组（仅 rule_type=images）
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_game_rules_game_id ON game_rules(game_id);
CREATE INDEX IF NOT EXISTS idx_game_rules_sort_order ON game_rules(sort_order);

-- 启用行级安全
ALTER TABLE game_rules ENABLE ROW LEVEL SECURITY;

-- 策略：所有人可读
CREATE POLICY "Anyone can view game rules" ON game_rules
  FOR SELECT USING (true);

-- 策略：管理员可增删改
CREATE POLICY "Admins can insert game rules" ON game_rules
  FOR INSERT WITH CHECK (auth.uid() IN (SELECT id FROM users WHERE role = 'admin'));

CREATE POLICY "Admins can update game rules" ON game_rules
  FOR UPDATE USING (auth.uid() IN (SELECT id FROM users WHERE role = 'admin'));

CREATE POLICY "Admins can delete game rules" ON game_rules
  FOR DELETE USING (auth.uid() IN (SELECT id FROM users WHERE role = 'admin'));